'use strict';var dy={TAB:0,Pi:1,gm:2},ey=function(a){Fb("MediaRouter.CastStreaming.Start.Success",a,dy)};var fy=lb("mr.mirror.cast.LogUploader"),hy=function(a,b,c){gy("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?stbtiq="+b:""},gy=function(a,b,c,d){if(0==b.size)fy.info("Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);pk("https://clients2.google.com/cr/report",function(a){a=a.target;var b=null;zk(a)?(b=Ak(a),fy.info("Upload to Crash succeeded: "+
b)):fy.info("Upload to Crash failed. HTTP status: "+a.Oa());d&&d(b)},"POST",e,void 0,3E4)}};var iy=function(){this.a=0;kh(this)},ky=function(){jy||(jy=new iy);return jy},ly=function(){var a=ky(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.a&&c&&d-a.a<c?!1:Math.random()<b.fraction};iy.prototype.oa=function(){return"mirror.cast.LogUtils"};iy.prototype.La=function(){return[void 0,{lastAutoSubmitMillis:this.a}]};iy.prototype.Pa=function(){var a=ih(this);this.a=a&&a.lastAutoSubmitMillis||0};var jy=null;lb("mr.mirror.cast.LogUtils");var my=lb("mr.NetworkUtils"),ny=function(a,b){return Of?new Promise(function(c,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(a){chrome.runtime.lastError?(t(my,"Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+b+".")):(my.info("TDLS state changed: state = "+b+", status = "+a),c(a))})}):Promise.reject("TDLS feature not enabled.")};var oy=function(){this.a=Promise.resolve(1)},qy=function(a,b,c){return py(a,function(a){return a==b},c)},ry=function(a,b){var c=[3,4];return py(a,function(a){return-1!=c.indexOf(a)},b)},sy=function(a,b){a.a=a.a.catch(function(){return 1});return py(a,function(){return!0},b)},py=function(a,b,c){var d,e,f=new Promise(function(a,b){d=a;e=b});a.a=a.a.then(function(a){if(!b(a))return e(Error("Operation requires a different starting checkpoint than "+a)),Promise.resolve(a);var f=new ty(a);try{var g=c(f)}catch(q){g=
Promise.reject(q)}return g.then(function(a){return d(a)},function(a){return e(a)}).then(function(){if(null===f.a)throw Error("A prior operation that started at "+(a+" did not complete."));return f.a})},function(a){e(a);throw a;});return f},ty=function(a){this.b=a;this.a=null},uy=function(a,b){a.a="number"===typeof b?b:a.b};var vy={Lt:"OFFER",Iq:"ANSWER",fu:"PRESENTATION",Zr:"GET_STATUS",Tu:"STATUS_RESPONSE",Yr:"GET_CAPABILITIES",br:"CAPABILITIES_RESPONSE",Fu:"RPC"};var wy=function(){this.capabilities=this.status=this.a=this.error=this.rpc=this.result=this.type=this.b=this.sessionId=null},zy=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;xy(JSON.parse(a),function(a){b=yy(a)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},yy=function(a){var b=new wy;null!=a.sessionId&&(b.sessionId=String(a.sessionId));Ay(a.seqNum,function(a){b.b=a},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=la(Object.keys(vy)),e=d.next();!e.done;e=d.next())if(vy[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(Ga(atob(a.rpc))).map(function(a){return a.charCodeAt(0)}))}xy(a.error,function(a){b.error=By(a)},function(){throw Error('"error" must be an Object');});xy(a.answer,function(a){b.a=Cy(a)},function(){throw Error('"answer" must be an Object');});xy(a.status,function(a){b.status=Dy(a)},function(){throw Error('"status" must be an Object');
});xy(a.capabilities,function(a){b.capabilities=Ey(a)},function(){throw Error('"capabilities" must be an Object');});return b},xy=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},Ay=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},Fy=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(a){return"number"===typeof a})?b(a):c())},Gy=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(a){return String(a)})):c())},Hy=function(){this.l=null;this.a=[];this.b=
[];this.f=this.g=this.h=null},Cy=function(a){var b=new Hy;Ay(a.udpPort,function(a){b.l=a},function(){throw Error('"answer.udpPort" must be a number');});Fy(a.sendIndexes,function(a){b.a=a},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});Fy(a.ssrcs,function(a){b.b=a},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.h=String(a.IV));"receiverGetStatus"in a&&(b.g="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.f=String(a.castMode));
return b},Iy=function(){this.details=this.description=this.code=null},By=function(a){var b=new Iy;Ay(a.code,function(a){b.code=a},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));xy(a.details,function(a){b.details=a},function(){throw Error('"error.details" must be an Object');});return b},Jy=function(){this.b=this.a=null},Dy=function(a){var b=new Jy;Ay(a.wifiSnr,function(a){b.a=a},function(){throw Error('"status.wifiSnr" must be a number');
});Fy(a.wifiSpeed,function(a){b.b=a},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},Ky=function(){this.b=this.a=null},Ey=function(a){var b=new Ky;Gy(a.mediaCaps,function(a){b.a=a},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.b=a.map(function(a){var b;xy(a,function(a){b=Ly(a)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return b})}return b},My=function(){this.f=this.u=this.h=this.l=this.v=this.a=this.m=this.b=this.initDataTypes=this.g=null},Ly=function(a){var b=new My;"keySystemName"in a&&(b.g=String(a.keySystemName));Gy(a.initDataTypes,function(a){b.initDataTypes=a},function(){throw Error('"capabilities.initDataTypes" must be an array');});Gy(a.codecs,function(a){b.b=a},function(){throw Error('"capabilities.codecs" must be an array');});Gy(a.secureCodecs,function(a){b.m=a},function(){throw Error('"capabilities.secureCodecs" must be an array');
});Gy(a.audioRobustness,function(a){b.a=a},function(){throw Error('"capabilities.audioRobustness" must be an array');});Gy(a.videoRobustness,function(a){b.v=a},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.l=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.h=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.u=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.f=String(a.distinctiveIdentifierSupport));return b};var Ny=function(a){this.j=lb("mr.mirror.cast.MessageDispatcher");this.g=a;this.a=null;this.b=new Map;this.f=0},Oy=function(a,b,c){if(a.b.has(b))throw Error("Attempt to multiple-subscribe to the same response type: "+b);a.b.set(b,c);a.f=0;u(a.j,"Added subscriber for "+b+"-type messages.");a.a||(a.a=ns(a.g),a.a.onMessage=a.l.bind(a))},Py=function(a,b){a.b.delete(b)&&u(a.j,function(){return"Removed subscriber of "+b+"-type messages."});0==a.b.size&&a.a&&(a.a.Ja(),a.a=null)};
Ny.prototype.sendMessage=function(a){return this.a?"RPC"==a.type?this.a.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.a.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var Qy=function(a,b,c,d,e){var f=null,g=function(){Py(a,c);null!=f&&(clearTimeout(f),f=null)};try{Oy(a,c,function(a){e(a)&&g()})}catch(k){e(null,k);return}f=setTimeout(function(){g();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(a){g();e(null,a)})};
Ny.prototype.l=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=zy(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.b.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback ")+("was: "+d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);
10>this.f?t(this.j,b):u(this.j,b);++this.f}};var Ry=chrome.cast.streaming,Ty=function(a,b,c,d,e){this.F=a.sessionId;this.v=a.Of;this.ea=a.de;this.f=b;this.I=c;this.B=d;this.H=Sy(e,"onAnswer",this.v);this.J=Sy(e,"onSessionStop",this.v);this.j=lb("mr.mirror.cast.StreamingLaunchWorkflow");this.s=new oy;this.u=this.w=this.m=this.b=this.a=this.h=this.l=this.g=null};
Ty.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof Uy,f=b instanceof Uy;(e&&b&&!f||f&&a&&!e)&&hc("Mixing remoting and non-remoting tracks");return qy(this.s,1,function(e){d.g=a;d.l=b;d.h=c;d.j.info(function(){return"Launching streaming for "+Vy(d)+" "+("to a "+d.ea+".")});return Wy(d).then(d.A.bind(d)).then(function(a){return Xy(d,a).then(function(b){d.H();var c=Yy(d,b,a);d.a=Zy(d,d.a,c);d.b=Zy(d,d.b,c);if(!d.a&&!d.b)throw Error("Receiver did not select any offers from: "+
JSON.stringify(a));d.w=!!b.g;d.u=function(a,b){a==d.a?d.h.Rd("Audio stream (id="+a+") error: "+b):a==d.b&&d.h.Rd("Video stream (id="+a+") error: "+b)};Ry.rtpStream.onError.addListener(d.u);return $y(d,b,c)})}).then(function(){d.j.info(function(){return"Launched streaming for "+Vy(d)});d.h.ff(d);uy(e,2);return{zn:d.a,kq:d.b}})})};
Ty.prototype.stop=function(){var a=this;return sy(this.s,function(b){if(!a.g&&!a.l)return uy(b,1),Promise.resolve();a.j.info(function(){return"Stopping streaming for "+Vy(a)+"."});a.u&&(Ry.rtpStream.onError.removeListener(a.u),a.u=null);if(a.h){var c=a.h.Uf();a.h=null}else c=Promise.resolve();return c.then(function(){a.a&&(Ry.rtpStream.stop(a.a),Ry.rtpStream.destroy(a.a),a.a=null);a.b&&(Ry.rtpStream.stop(a.b),Ry.rtpStream.destroy(a.b),a.b=null);a.m&&(Ry.udpTransport.destroy(a.m),a.m=null);a.J();a.j.info(function(){return"Stopped streaming for "+
Vy(a)+"."});a.g=null;a.l=null;uy(b,1)})})};
var az=function(a,b){var c=JSON.stringify(b);return Promise.all([a.a&&new Promise(function(b){return Ry.rtpStream.getRawEvents(a.a,c,b)}),a.b&&new Promise(function(b){return Ry.rtpStream.getRawEvents(a.b,c,b)})]).catch(function(b){a.j.error("Unexpected error when calling getRawEvents()",b);return[]}).then(function(a){return new Blob(a.filter(function(a){return!!a}),{type:"application/gzip"})})},bz=function(a){return Promise.all([a.a&&new Promise(function(b){return Ry.rtpStream.getStats(a.a,b)}),a.b&&
new Promise(function(b){return Ry.rtpStream.getStats(a.b,b)})]).catch(function(b){a.j.error("Unexpected error when calling getStats()",b);return[]}).then(function(a){return Object.assign.apply(Object,[].concat([{}],Ga(a.filter(function(a){return!!a}))))})},Vy=function(a){if(a.g&&a.l)var b="audio+video ";else if(a.g)b="audio-only ";else if(a.l)b="video-only ";else return"stopped";return a.g instanceof Uy||a.l instanceof Uy?b+"remoting":b+"streaming"},Wy=function(a){return new Promise(function(b){var c=
function(c,e,f){c&&!a.g&&(Ry.rtpStream.destroy(c),c=null);e&&!a.l&&(Ry.rtpStream.destroy(e),e=null);a.j.info(function(){return"Created Cast Streaming session: audioStreamId="+c+", videoStreamId="+e+"."});a.a=c;a.b=e;a.m=f;b()};a.g instanceof Uy||a.l instanceof Uy?Ry.session.create(null,null,c):Ry.session.create(a.g,a.l,c)})};
Ty.prototype.A=function(){for(var a=qv(),b=qv(),c=[],d=la([this.a,this.b]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.a,g=f?127:96,k=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,m=f?48E3:9E4,q=la(Ry.rtpStream.getSupportedParams(e)),z=q.next();!z.done;z=q.next())z=z.value,z.payload.payloadType=g,z.payload.maxLatency=this.f.maxLatencyMillis,z.payload.minLatency=this.f.minLatencyMillis,z.payload.animatedLatency=this.f.animatedLatencyMillis,z.payload.ssrc=
k,z.payload.clockRate=m,z.payload.aesKey=a,z.payload.aesIvMask=b,f?(z.payload.channels=2,z.payload.maxBitrate=this.f.audioBitrate,z.payload.maxFrameRate=100):(z.payload.minBitrate=this.f.minVideoBitrate,z.payload.maxBitrate=this.f.maxVideoBitrate,z.payload.maxFrameRate=this.f.maxFrameRate),c.push(new cz(e,z));return c};
var Zy=function(a,b,c){b&&!c.some(function(a){return a.Se==b})&&(t(a.j,"Destroying RTP stream not selected by the receiver: id="+b),Ry.rtpStream.destroy(b),b=null);return b},Xy=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var g=b[f].params,k={index:f,codecName:g.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:g.payload.payloadType,ssrc:g.payload.ssrc,targetDelay:g.payload.animatedLatency,aesKey:g.payload.aesKey,aesIvMask:g.payload.aesIvMask,timeBase:"1/"+
g.payload.clockRate,receiverRtcpEventLog:a.f.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.f.dscpEnabled&&(k.receiverRtcpDscp=46);127==g.payload.payloadType?Object.assign(k,{type:"audio_source",bitRate:0<g.payload.maxBitrate?1E3*g.payload.maxBitrate:60*g.payload.maxFrameRate+g.payload.clockRate*g.payload.channels,sampleRate:g.payload.clockRate,channels:g.payload.channels}):Object.assign(k,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*g.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*g.payload.maxBitrate,resolutions:[{width:a.f.maxWidth,height:a.f.maxHeight}]});e.push(k)}var m=a.g instanceof Uy||a.l instanceof Uy?"remoting":"mirroring",q={type:"OFFER",sessionId:a.F,seqNum:Jk(a.I),offer:{castMode:m,receiverGetStatus:!0,supportedStreams:e}};a.j.info(function(){return"Sending OFFER message: "+JSON.stringify(q)});Qy(a.B,q,"ANSWER",1E4,function(b,e){if(null==b)d(e);else if("ok"==b.result&&b.a){if(b.b!=q.seqNum)return t(a.j,"Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(b)),!1;((e=b.a.f)&&e!=m||!e&&"mirroring"!=m)&&a.j.error("Expected receiver to ANSWER with castMode="+m+", but got: "+e);u(a.j,function(){return"Received ANSWER: "+JSON.stringify(b)});c(b.a)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(b)));return!0})})},Yy=function(a,b,c){if(b.a.length!=b.b.length)return a.j.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.a.length;e={candidate:e.candidate},++f){var g=b.a[f];if(0>g||g>=
c.length)return a.j.error("Receiver selected invalid index ("+g+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.candidate=c[g];if(d.some(function(a){return function(b){return b.Se==a.candidate.Se}}(e)))return a.j.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.candidate.params.payload.feedbackSsrc=b.b[g];if(d.some(function(a){return function(b){return b.params.payload.feedbackSsrc==a.candidate.params.payload.feedbackSsrc}}(e)))return a.j.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+
JSON.stringify(b)),[];d.push(e.candidate)}return d},$y=function(a,b,c){var d=null,e=function(){d&&(Ry.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(e,g){var f=b.l||2344;a.j.info(function(){return"Starting RTP streams to receiver at "+(a.v+":"+f)+(" for selected offers: "+JSON.stringify(c))});var m=a.m||-1;a.f.dscpEnabled&&(a.j.info("Enabled DSCP in sender."),Ry.udpTransport.setOptions(m,{DSCP:!0}));Ry.udpTransport.setDestination(m,{address:a.v,port:f});var q=new Set(c.map(function(a){return a.Se}));
d=function(a){q.delete(a);0==q.size&&e()};Ry.rtpStream.onStarted.addListener(d);m=la(c);for(var z=m.next();!z.done;z=m.next())z=z.value,Ry.rtpStream.toggleLogging(z.Se,a.f.enableLogging),Ry.rtpStream.start(z.Se,z.params);setTimeout(function(){g(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(a){e();throw a;})},Sy=function(a,b,c){var d=this;return a&&b in a?function(){try{a[b](c)}catch(e){d.j.error("Error from testHooks."+b,e)}}:function(){}},cz=function(a,b){this.Se=
a;this.params=b},Uy=function(){};var fz=function(a,b,c,d,e,f){this.h=a;this.A=dz(b,this.h.bc);this.w=new Ty(this.h.bc,c,d,e,f);this.v=e;this.g=new oy;this.b=new ez;this.m=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.j=lb("mr.mirror.cast.MediaRemoter");this.u=this.a=this.l=this.f=this.s=null};
fz.prototype.Ua=function(a,b){var c=this;return qy(this.g,1,function(d){c.s=a;c.f=b;var e=c.m.createInterfacePtrAndBind();c.m.setConnectionErrorHandler(function(){c.j.info("Remoter mojo pipe connection error.");gz(c)});c.a=new mojo.MirrorServiceRemotingSourcePtr;var f=lg(c.h.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+c.h.mediaSource);c.j.info("Connecting remoter to browser: tabId="+f);(pg.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,mojo.makeRequest(c.a));
c.a.ptr.setConnectionErrorHandler(function(){c.j.info("RemotingSource mojo pipe connection error.");gz(c)});c.a.onSinkAvailable(c.A);uy(d,2);return Promise.resolve()})};var gz=function(a){return sy(a.g,function(b){a.a&&(a.a.ptr.reset(),a.a=null);var c=a.l;a.l=null;a.f=null;a.s=null;a.m.close();return new Promise(function(d){window.setTimeout(function(){hz(a).then(function(){uy(b,1);d();c&&c()})},250)})})};fz.prototype.Op=function(a){iz(this.b,a)};fz.prototype.sendMessageToSink=fz.prototype.Op;
fz.prototype.ff=function(a){this.f&&this.f.ff(a)};fz.prototype.Uf=function(){return this.f?this.f.Uf():Promise.resolve()};fz.prototype.Rd=function(a,b){this.j.error("Error during streaming: "+a,b);if(this.a)this.a.onError();gz(this)};
fz.prototype.start=function(){var a=this,b=!1;this.j.info(function(){b=!0;return"Starting next media remoting session."});b&&jz(this.b,function(b){return a.j.info(b)});kz(this.b);qy(this.g,2,function(b){return(0,a.s)().then(function(c){a.l=c;Oy(a.v,"RPC",function(b){if(b.rpc){var c=a.b;b=b.rpc;c.h&&(++c.u,c.b+=b.length,c.h(b))}});uy(b,3)}).catch(function(c){return hz(a).then(function(){uy(b);throw c;})})}).then(function(){a.j.info("Remoting started successfully.")}).catch(function(b){a.j.error("Failed to start remoting",
b);a.a.onError()})};fz.prototype.start=fz.prototype.start;
fz.prototype.Zp=function(a,b){var c=this;return qy(this.g,3,function(d){return c.w.start(a?new Uy:null,b?new Uy:null,c).then(function(a){lz(c.b,function(a){return c.v.sendMessage(a)},function(a){c.a.onMessageFromSink(a)});uy(d,4);return{audio_stream_id:a.zn||-1,video_stream_id:a.kq||-1}}).catch(function(a){return hz(c).then(function(){uy(d);throw a;})})}).catch(function(a){c.j.error("Failed to start remoting streams",a);gz(c);return{audio_stream_id:-1,video_stream_id:-1}})};
fz.prototype.startDataStreams=fz.prototype.Zp;fz.prototype.stop=function(a){var b=this;ry(this.g,function(c){b.a.onStopped(a);return hz(b).then(function(){b.j.info("Remoting stopped.");uy(c,5);(0,b.l)().then(function(){return qy(b.g,5,function(a){if(b.a)b.a.onSinkAvailable(b.A);uy(a,2);return Promise.resolve()})}).catch(function(a){throw a;});b.l=null})}).catch(function(a){b.j.error("Failed to stop remoting: ",a);gz(b)})};fz.prototype.stop=fz.prototype.stop;
fz.prototype.Sn=function(){null===this.u&&(this.u=De(this.h.bc.Of).then(function(a){return a.b||!1}));return this.u.then(function(a){return{rate:(a?1E7:5E6)/8}})};fz.prototype.estimateTransmissionCapacity=fz.prototype.Sn;
var hz=function(a){return a.w.stop().then(function(){Py(a.v,"RPC");mz(a.b);nz(a.b)})},dz=function(a,b){var c=this,d=new mojo.RemotingSinkMetadata;d.features=[];d.friendly_name=b.Yp||"";d.audio_capabilities=[];d.video_capabilities=[];var e=mojo.RemotingSinkAudioCapability,f=mojo.RemotingSinkVideoCapability,g=d.audio_capabilities,k=d.video_capabilities,m=b.de||"";(a.a||[]).forEach(function(a){switch(a){case "audio":g.push(e.CODEC_BASELINE_SET);break;case "aac":g.push(e.CODEC_AAC);break;case "opus":g.push(e.CODEC_OPUS);
break;case "video":k.push(f.CODEC_BASELINE_SET);break;case "4k":k.push(f.SUPPORT_4K);break;case "h264":k.push(f.CODEC_H264);break;case "vp8":k.push(f.CODEC_VP8);break;case "vp9":m.startsWith("Chromecast Ultra")&&k.push(f.CODEC_VP9);break;case "hevc":m.startsWith("Chromecast Ultra")&&k.push(f.CODEC_HEVC);break;default:c.j.info("Unknown mediaCap name: "+a)}});b.de&&"Chromecast Ultra"==b.de&&k.push(f.SUPPORT_4K);return d},ez=function(){this.h=this.l=this.a=null;this.v=this.b=this.u=this.f=this.m=0;this.g=
null},kz=function(a){a.a=[];oz(a,performance.now())},lz=function(a,b,c){a.l=b;a.h=c;a.a?(b=a.a,a.a=null,b.forEach(function(b){return iz(a,b.data).then(b.Qp,b.cl)})):oz(a,performance.now())},mz=function(a){if(a.a){var b=Error("Stop before delivering pending message");a.a.forEach(function(a){return a.cl(b)});a.a=null}a.l=null;a.h=null},iz=function(a,b){if(a.l){var c=btoa(String.fromCharCode.apply(null,b));++a.m;a.f+=b.length;return a.l({type:"RPC",rpc:c})}return a.a?new Promise(function(c,e){a.a.push({data:b,
Qp:c,cl:e})}):Promise.reject(Error("RPC pipe not started"))},jz=function(a,b){nz(a);a.g=setInterval(function(){if(a.a)var c=a.a.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.v)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.m+" messages ("+Math.round(a.f/d)+" bytes/sec) and ")+("received "+a.u+" messages ("+Math.round(a.b/d)+" ")+"bytes/sec).";oz(a,c);c=d}b(c)},3E4)},nz=function(a){null!=a.g&&(clearInterval(a.g),a.g=null)},oz=function(a,b){a.m=0;a.f=0;a.u=0;
a.b=0;a.v=b};var pz=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},qz=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var rz=function(a,b,c,d,e){this.f=new Ty(a,b,c,d,void 0===e?null:e);this.j=lb("mr.mirror.cast.MediaStreamer");this.l=new oy;this.g=this.b=this.a=this.h=null};rz.prototype.start=function(a,b){var c=this;return qy(this.l,1,function(d){c.h=a;c.a=pz(a);c.a&&"ended"==c.a.readyState&&(c.a=null);c.b=qz(a);c.b&&"ended"==c.b.readyState&&(c.b=null);if(!c.a&&!c.b)return uy(d),Promise.reject(Error("No MediaStream tracks to stream."));c.g=b;return c.f.start(c.a,c.b,c.g).then(function(){return uy(d,2)})})};
rz.prototype.stop=function(){var a=this;return sy(this.l,function(b){return a.f.stop().then(function(){a.a=null;a.b=null;a.h=null;a.g=null;uy(b,1)})})};var sz=function(a){return qy(a.l,2,function(b){a.j.info("Suspending media streaming...");return a.f.stop().then(function(){a.j.info("Suspended media streaming.");uy(b,3)})})};
rz.prototype.resume=function(){var a=this;return qy(this.l,3,function(b){a.a&&"ended"==a.a.readyState&&(a.a=null);a.b&&"ended"==a.b.readyState&&(a.b=null);if(!a.a&&!a.b)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.j.info("Resuming media streaming...");return a.f.start(a.a,a.b,a.g).then(function(){a.j.info("Resumed media streaming.");uy(b,2)})})};var tz=function(a,b,c){this.l=a;this.g=b;this.f=c;this.j=lb("mr.mirror.cast.WifiStatusMonitor");this.a=null;this.b=[]};tz.prototype.start=function(){var a=this;null==this.a&&(u(this.j,"Starting Wifi Status Monitoring."),this.b=[],Oy(this.f,"STATUS_RESPONSE",function(b){return uz(a,b)}),this.a=setInterval(function(){return vz(a)},12E4),vz(this))};tz.prototype.stop=function(){null!=this.a&&(u(this.j,"Stopping Wifi Status Monitoring."),clearInterval(this.a),this.a=null,Py(this.f,"STATUS_RESPONSE"))};
var uz=function(a,b){if(null!=a.a)if(b.status){var c={};null!=b.status.a&&(c.wifiSnr=b.status.a);null!=b.status.b&&(c.wifiSpeed=b.status.b[3]);0==Object.keys(c).length?t(a.j,function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.b.length&&a.b.shift(),a.b.push(c),a.j.info(function(){return"Current Wifi status: "+JSON.stringify(c)}))}else t(a.j,function(){return"Ignoring response without status: "+JSON.stringify(b)})},vz=function(a){a.f.sendMessage({type:"GET_STATUS",
sessionId:a.l,seqNum:Jk(a.g),get_status:["wifiSnr","wifiSpeed"]})};var wz=function(a,b,c,d){this.B=b.Of;this.u={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:Mg(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.de};this.A=c;this.w=d;this.g=this.b=this.m=this.h=this.l=this.v=this.f=null;this.a=[]};wz.prototype.ff=function(a){null!=this.b&&clearInterval(this.b);this.f=a;this.v=Date.now();this.b=setInterval(this.s.bind(this,a),9E5)};
wz.prototype.Uf=function(){null!=this.b&&(clearInterval(this.b),this.b=null);if(null!=this.f){var a=this.s(this.f);this.f=null;return a}return Promise.resolve()};wz.prototype.Rd=function(a,b){null==this.l&&(this.l=Date.now(),"function"===typeof a?this.h=a():"string"===typeof a&&(this.h=a),b&&"string"===typeof b.stack&&(this.m=b.stack))};
var yz=function(a,b){return(null==a.f?Promise.resolve():a.s(a.f)).then(function(){var c=b.map(function(b){b=xz(a,b);var c=b.map(function(a){return a.events}).filter(function(a){return null!=a}),d=["["];b.map(function(a){return a.Re}).forEach(function(a,b){0<b&&d.push(",");d.push(a)});d.push("]");return{events:new Blob(c,{type:"application/gzip"}),Re:new Blob(d,{type:"application/json"})}});a.a=[];return c})};
wz.prototype.s=function(a){var b=this;if(null!=this.g)return this.g;var c=De(this.B).then(function(c){c={receiverVersion:c.a,receiverConnected:c.g,receiverOnEthernet:c.b,receiverHasUpdatePending:c.f,receiverUptimeSeconds:c.l};Object.assign(c,b.u);var d=Date.now();Object.assign(c,{startTime:b.v,endTime:d,activity:Vy(a),receiverWifiStatus:Array.from(b.w.b)});b.v=d;null!=b.l&&(Object.assign(c,{streamingErrorTime:b.l,streamingErrorMessage:b.h,streamingErrorCause:b.m}),b.l=null,b.h=null,b.m=null);return c});
return(this.g=Promise.all([c.then(function(b){return az(a,b)}),c,bz(a)]).then(function(a){var c=la(a);a=c.next().value;var d=c.next().value;c=c.next().value;b.a.push({events:a,Re:new Blob([JSON.stringify(Object.assign({tags:d},c))],{type:"application/json"})});b.a=xz(b,b.A);b.g=null}))||Promise.resolve()};
var xz=function(a,b){b-=2;for(var c=[],d=a.a.length-1;0<=d;--d){b-=a.a[d].Re.size+1;if(0>b)break;c.push({events:null,Re:a.a[d].Re});if(null!=a.a[d].events){var e=a.a[d].events.size;b>=e&&(c[c.length-1].events=a.a[d].events,b-=e)}}return c.reverse()};var zz=function(a,b,c,d){d=void 0===d?null:d;Jg.call(this,b);var e=b.bc;this.v=e.sessionId;this.I=e.Of;this.A=a;this.F=d;this.j=lb("mr.mirror.cast.Session");this.m=new oy;this.u=new Ik("mirror.cast.SeqNumGenerator");this.h=new Ny(b.id);this.l=new rz(e,this.A,this.u,this.h,this.F);this.g=null;this.a=new wz(a,e,c,new tz(this.v,this.u,this.h));this.f=!1;this.s=null};Fa(zz,Jg);h=zz.prototype;
h.start=function(a){var b=this;return qy(this.m,1,function(c){var d=new ub("MediaRouter.CastStreaming.Session.Launch");return Az(b).then(function(c){b.f=c;return b.l.start(a,b)}).then(function(){if(b.l.f.w){var a=b.a;a.u.tdlsIsOn=b.f;a.w.start();Bz(b)}else b.a.u.tdlsIsOn=b.f;d.a();b.s=new Bb("MediaRouter.CastStreaming.Session.Length");uy(c,2);return b})})};
h.stop=function(){var a=this;return sy(this.m,function(b){a.s&&(a.s.a(),a.s=null);a.a.w.stop();return a.l.stop().then(function(){return a.g?gz(a.g):Promise.resolve()}).then(function(){a.g=null;return a.f?Cz(a):Promise.resolve()}).then(function(){a.f=!1;uy(b,4)})})};
h.bl=function(){var a={sessionId:this.v,seqNum:Jk(this.u),type:"PRESENTATION",icons:[]};this.B&&(a.title=this.B);this.iconUrl&&!this.w&&a.icons.push({url:this.iconUrl});this.j.info("Sending session metadata update to receiver: "+this.v);this.h.sendMessage(a)};h.ff=function(a){this.a.ff(a)};h.Uf=function(){return this.a.Uf()};h.Rd=function(a,b){this.a.Rd(a,b);this.j.error(a,b);this.stop()};
var Dz=function(a,b){return yz(a.a,b)},Az=function(a){return a.A.useTdls?ny(a.I,!0).then(function(b){if("Connected"==b)return a.j.info("Successfully enabled TDLS."),!0;t(a.j,"Did not enable TDLS: result="+b);return!1}).catch(function(b){t(a.j,"Error while calling enableTDLS()",b);return!1}):Promise.resolve(!1)},Cz=function(a){return ny(a.I,!1).catch(function(b){return a.j.error("Error while turning TDLS back off",b)})},Bz=function(a){Ez(a).then(function(b){(b.a||[]).includes("video")?Fz(a,b):t(a.j,
function(){return"Receiver incapable of Media Remoting: "+JSON.stringify(b)})}).catch(function(b){t(a.j,"None/Invalid capabilites response. Media Remoting disabled.",b)})},Ez=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.v,seqNum:Jk(a.u)};a.j.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});Qy(a.h,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+
JSON.stringify(e))),!0;if(e.b!=d.seqNum)return a.j.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+JSON.stringify(e)}),!1;u(a.j,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},Fz=function(a,b){qy(a.m,2,function(c){var d=a.b.bc.de||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return t(a.j,"HACK: Media Remoting disabled because the receiver model--"+('"'+d+'" according to discovery--is not a Chromecast.')),
uy(c),Promise.resolve();a.g=new fz(a.b,b,a.A,a.u,a.h,a.F);return a.g.Ua(a.ea.bind(a),a).catch(function(b){a.j.error("Media Remoting start failed: "+b.message,b)}).then(function(){return uy(c)})})};zz.prototype.ea=function(){var a=this;return qy(this.m,2,function(b){return new Promise(function(c,d){sz(a.l).then(function(){uy(b,3);c(a.H.bind(a))}).catch(function(b){a.Rd("Failed to suspend MediaStreamer before starting remoting",b);d(b)})})})};
zz.prototype.H=function(){var a=this;return qy(this.m,3,function(b){return new Promise(function(c,d){a.l.resume().then(function(){uy(b,2);c()}).catch(function(b){a.Rd("Failed resume MediaStreamer after ending remoting mode",b);d(b)})})})};var Gz=function(){zg.call(this,"cast_streaming")};Fa(Gz,zg);h=Gz.prototype;h.getName=function(){return"cast_streaming"};h.qg=function(a,b){return new zz(a,b,Math.max(20969472,9351424),null)};h.Yg=function(){ey(0)};h.Vg=function(){ey(1)};h.ri=function(){ey(2)};h.Wg=function(){Eb("MediaRouter.CastStreaming.Session.End")};h.Xg=function(a){Fb("MediaRouter.CastStreaming.Start.Failure",a,Uf)};h.Jf=function(){Eb("MediaRouter.CastStreaming.Stream.End")};
h.oh=function(a){var b=this;return(new Promise(function(a){return chrome.metricsPrivate.getIsCrashReportingEnabled(a)})).then(function(c){var d=c&&ly(),e=[9351424];d&&e.push(20969472);return Dz(a,e).then(function(a){var e=a[a.length-1];a=th(a[0].events).catch(function(a){b.G.error("Failed to persist events Blob.",a)});d&&0<e.events.size?hy(e.events,void 0,b.Fo.bind(b)):c&&gy("stats.json",e.Re,void 0,void 0);return a})})};h.Fo=function(a){a&&(ky().a=Date.now())};
h.Zh=function(a){this.G.info("Received message to upload logs for "+a);return this.a?Dz(this.a,[20969472]).then(function(b){b=la(b).next().value;return 0==b.events.size?"":hy(b.events,a)}):Promise.resolve(Hz(this,a))};
var Hz=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return th(new Blob),a.G.info("Uploading saved logs for feedback."),hy(c,b)},Iz=new Gz;yg("mr.mirror.cast.Service",Iz);
